FE: Add cards to columns
hatchways/team-santorini pull request #64
Opened 2021-06-24 17:39 UTC by samimsu

### What this PR does (required):
- add cards to columns
- move cards between columns
- move columns around

### Screenshots / Videos (required):
https://www.loom.com/share/cfe33d4831f34ea4a8d8135459ea9cfa

### Any information needed to test this feature (required):
- Login and add cards to a column

2021-06-24 18:07 UTC, felix-quinn commented on server/controllers/auth.js
> +  const fullBoardById = await Board.findById(user.board)
This part is no longer needed.

2021-06-24 18:42 UTC, felix-quinn commented on client/src/pages/Dashboard/Dashboard.tsx
> +          <BoardUI boardData={initialData} />
I believe it's a better idea for the Board itself to load the board data, mock or otherwise.

2021-06-24 18:43 UTC, felix-quinn commented on client/src/interface/User.ts
> +  board: {
Don't forget to remove this before merging after refactoring the code to use the existing Board, Column, and Card interfaces.

2021-06-24 19:04 UTC, felix-quinn requested changes
There's a handful of spots that don't use the new interfaces and board context yet. Do you want help with that or are you planning to add that later today?

2021-06-24 19:12 UTC, samimsu commented
> There's a handful of spots that don't use the new interfaces and board context yet. Do you want help with that or are you planning to add that later today?

Was adding that now.

2021-06-25 00:02 UTC, moffatethan commented on client/src/components/BoardUI/initial-data.js
> +//     'task-2': { id: 'task-2', title: 'Code' },
This can be removed

2021-06-25 00:03 UTC, moffatethan commented on client/src/components/BoardUI/Card.jsx
> +// const Container = ({ children }) => <div className='task-container'>{children}</div>
If this isn't used it doesn't need to be here

2021-06-25 00:04 UTC, moffatethan commented on client/src/components/BoardUI/Column.jsx
> +// const Title = ({ children }) => <h3 className='column-title'>{children}</h3>;
Same here

2021-06-25 00:05 UTC, moffatethan reviewed
Left some comments but otherwise it's looking good

2021-06-25 04:24 UTC, samimsu commented
> There's a handful of spots that don't use the new interfaces and board context yet. Do you want help with that or are you planning to add that later today?

Tried but couldn't get it to work. Can we make a separate issue for this?

2021-06-25 05:00 UTC, merged